django_webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),
]

first_app/urls.py
from django.urls import path
from . import views

app_name = 'first_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('album/add/', views.CreateAlbum.as_view(), name='add-album'),
    path('album/<int:pk>/', views.UpdateAlbum.as_view(), name='update-album'),
    path('album/<int:pk>/delete/', views.DeleteAlbum.as_view(), name='delete-album'),
]

first_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class ALbum(models.Model):
    artist = models.CharField(max_length=250)
    albumTitle = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    albumImage = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('first_app:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.albumTitle + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(ALbum, on_delete=models.CASCADE)
    fileType = models.CharField(max_length=15)
    songTitle = models.CharField(max_length=100)
    favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.songTitle

first_app/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import ALbum


class IndexView(generic.ListView):
    template_name = 'first_temp.html'

    def get_queryset(self):
        return ALbum.objects.all()


class DetailView(generic.DetailView):
    model = ALbum
    template_name = 'detail.html'


class CreateAlbum(CreateView):
    model = ALbum
    template_name = 'album_form.html'
    fields = ['artist', 'albumTitle', 'genre', 'albumImage']


class UpdateAlbum(UpdateView):
    model = ALbum
    template_name = 'album_form.html'
    fields = ['artist', 'albumTitle', 'genre', 'albumImage']


class DeleteAlbum(DeleteView):
    model = ALbum
    success_url = reverse_lazy('first_app:index')


# from django.shortcuts import render, get_object_or_404
# from .models import ALbum, Song

# # Create your views here.

# def index(req):
#     all_album = ALbum.objects.all()
#     return render(req, 'first_temp.html', {'all_album': all_album})

# def detail(req, album_id):
#     # album = ALbum.objects.get(pk=album_id)
#     album = get_object_or_404(ALbum, pk=album_id)
#     return render(req, 'detail.html', {'album': album})

# def favourite(req, album_id):
#     album = get_object_or_404(ALbum, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=req.POST['song'])
#     except (KeyError, Song.DoesNotExist):
#         return render(req, 'detail.html', {
#             'album': album,
#             'error_message': 'You do not have the song!',
#         })
#     else:
#         selected_song.favourite = True
#         selected_song.save()
#         return render(req, 'detail.html', {'album': album})

first_app/templates/album_form.html
{% extends "index.html" %} {% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4>Add a New Album</h4>
                </div>
                {% if error_message %}
                <p>
                    <strong>{{ error_message }}</strong>
                </p>
                {% endif %}
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %} {% include "form-template.html" %}
                        <div class="form-group">
                            <div class="row justify-content-md-center">
                                <div class="col-sm-10 offset-sm-2">
                                    <button class="btn btn-success" type="submit">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- <div class="card-footer">
                </div> -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

first_app/templates/detail.html
{% extends "index.html" %} {% block body %}
<div class="container-fluid">
    <div class="row">
        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="card" style="width: 18rem;">
                <a href="{{ album.id }}/">
                    {% if album.albumImage %}
                    <img class="card-img-top" src="{{ album.albumImage }}" alt="{{ album.albumTitle }}"> {% else %}
                    <h3>No image to display</h3>
                    {% endif %}
                </a>
                <div class="card-body">
                    <h5 class="card-title">{{ album.albumTitle }} - {{ album.artist }}</h5>
                    <p class="card-text">{{ album.genre }}</p>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-tabs" style="margin-bottom: 10px;">
                <li role="presentation" class="nav-item">
                    <a class="nav-link active" href="{% url 'first_app:detail' album.id %}">View All</a>
                </li>
                <li role="presentation">
                    <a class="nav-link" href="#" style="color: wheat">Add New Song</a>
                </li>
            </ul>

            <div class="card">
                <div class="card-body">
                    <h3>All Songs</h3>
                    {% if error_message %}
                    <p>
                        <strong>{{ error_message }}</strong>
                    </p>
                    {% endif %}

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Title</th>
                                    <!-- <th scope="col">Audio File</th> -->
                                    <th scope="col">File Type</th>
                                    <!-- <th scope="col">Actions</th> -->
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in album.song_set.all %}
                                <tr>
                                    <td>{{ song.songTitle }}</td>
                                    <td>{{ song.fileType}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

first_app/templates/first_temp.html
{% extends "index.html" %} {% block body %}

<div class="container-fluid">
    <div class="row">
        {% if object_list %} {% for album in object_list %}
        <div class="col-lg-3">
            <!-- <div class="card">
                    <a href="{{ album.id }}/">
                        <img class="card-img-top" src="{{ album.albumImage }}">
                    </a>
                    <div class="card-block">
                        <h4 class="card-title">{{ album.albumTitle }} - {{ album.artist }}</h4>
                        <p class="card-text">{{ album.genre }}</p>
                    </div>
                </div> -->
            <div class="card" style="width: 18rem;">
                <a href="{{ album.id }}/">
                    <img class="card-img-top" src="{{ album.albumImage }}" alt="{{ album.albumTitle }}">
                </a>
                <div class="card-body">
                    <h5 class="card-title">{{ album.albumTitle }} - {{ album.artist }}</h5>
                    <p class="card-text">{{ album.genre }}</p>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-4 p-0 m-0">
                            <a href="{{ album.id }}/" class="btn btn-primary btn-sm">
                                <i class="fas fa-info-circle"></i>&nbsp; Details
                            </a>
                        </div>
                        <div class="col-sm-4 p-0">
                            <form action="{% url 'first_app:delete-album' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <i class="fas fa-eraser"></i>&nbsp; Delete
                                </button>
                            </form>
                        </div>
                        <div class="col-sm-4"></div>
                    </div>
                </div>
            </div>
            <div style="margin: 20px;"></div>
            <!-- <div class="card-header">
                    <h2>{{ album.albumTitle }}</h2>
                </div>
                <div class="card-body m-0 p-0">
                    <img class="img-fluid rounded mx-auto d-block" src="{{ album.albumImage }}" alt="{{ album.albumTitle }}">
                </div>
                <div class="card-footer">
                    <h4>{{ album.artist }}</h4>
                    <h5>{{ album.genre }}</h5>
                </div> -->
        </div>
        {% endfor %} {% endif %}
    </div>
</div>
<!-- 
    {% for album in object_list %}

        <a href="{{ album.id }}/ ">{{ album.albumTitle }}</a>

    {% endfor %} -->
{% endblock %}

first_app/templates/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="row">
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <span class="text-danger small"> {{ field.error_messages }}</span>
        </div>
    </div>
</div>
{% endfor %}

first_app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Demo</title>

    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'first_app/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Lobster|Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
        crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- Brand/logo -->
        <a class="navbar-brand" style="font-family: 'Lobster', cursive" href="{% url 'first_app:index' %} ">Demo</a>
        <button class="navbar-toggler " type="button " data-toggle="collapse " data-target="#collapsibleNavbar ">
            <span class="navbar-toggler-icon "></span>
        </button>
        <!-- Links -->
        <div class="collapse navbar-collapse " id="collapsibleNavbar ">
            <ul class="navbar-nav mr-auto ">
                <li class="nav-item active ">
                    <a class="nav-link " href="{% url 'first_app:index' %} ">
                        <i class="fas fa-compact-disc " aria-hidden="true "></i>&nbsp; Album
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link " href="# ">
                        <i class="fas fa-music " aria-hidden="true "></i>&nbsp; Music
                    </a>
                </li>
                <form class="form-inline my-2 my-lg-0 " action="# " role="search " method="GET ">
                    <div class="form-group ">
                        <input class="form-control mr-sm-2 " type="text " name="q " value=" ">
                    </div>
                    <button class="btn btn-outline-success my-2 my-sm-0 ">Search</button>
                </form>
            </ul>
            <ul class="navbar-nav ">
                <li class="nav-item ">
                    <a class="nav-link " href="{% url 'first_app:add-album' %}">
                        <i class="fas fa-cloud-upload-alt " aria-hidden="true "></i>&nbsp; Add Album
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link " href="# ">
                        <i class="fas fa-sign-out-alt " aria-hidden="true "></i>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div style="margin: 20px;"></div>
    {% block body %} {% endblock %}
</body>

</html>